# Generated by Django 4.2.3 on 2023-07-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='book_cover'),
        ),
        migrations.AddField(
            model_name='book',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='book_cover'),
        ),
        migrations.AddField(
            model_name='book',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='book_cover'),
        ),
    ]
